# Site
repository: csanjiti1.sanjiti.github.io


# Personal info
name: Sanjiti Chakraborty
title: Business Reporting Analyst
email: csanjiti@gmail.com
phone: 773-677-8233



# About Section
# about_title: About Me
about_profile_image: images/F4619C38-93DD-4E6E-8656-69A6E0270DFC.jpg
About_Me: | # this will include new lines to allow paragraphs
Hello All! My name is sanjiti , currently working as Business reporting analyst for Tata Consultancy Services, Client Partner-CNA
Results-oriented and detail-driven BI Developer with 5 years of experience creating and implementing end-to-end business intelligence solutions. Proven track record of optimizing 
data integrity, and driving data-driven decision-making. Seeking to contribute technical expertise and analytical skills to a dynamic organization focused on harnessing the power of
data for strategic advantage.


# SkillSet
Skill: | # this will include new lines to allow paragraphs
   - **Data** **Management**: Database Design and Management, Data Analysis, , Visualization and Data Insights, Data Warehousing, Data Modeling
   - **Data Visualization**: Excel, Tableau, PowerBI, Crystal Report, SSRS,Looker
   - **BI and Reporting tools**: MS Power BI, Tableau, Excel VBA, VLOOKUP
   - **Data Analytics**: Excel, SQL
   - **Database**: MS Access, Oracle SQL developer, MYSQL, MS SQL,Postgres
   - **ETL Tools**: Informatica Powercenter
   - **Web Analytics**: Google Analytics
   -MS Project, Incident Analysis,Change Management, ServiceNow,JIRA,Confluence,LucidChart,MS Visio
   



